# Generated by Django 3.1.2 on 2020-11-06 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0003_auto_20201025_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='edad',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
