# Generated by Django 3.1.2 on 2020-11-06 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0004_auto_20201105_2312'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileWeb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('edad', models.IntegerField()),
                ('email', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='edad',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
    ]
